In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

body = client_b844105826ea467292f9d8a53be925e7.get_object(Bucket='edx1-donotdelete-pr-rmsy7vzqm6dj4d',Key='MN_18v1.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_1 = pd.read_csv(body)
df_data_1.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (20,23,24,26,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_Flag,PFIRM15_Flag,Version
0,MN,1,10,101,5.0,1011.0,2.0,1.0,10004.0,E007,...,Y,199 999,10101.0,NaN,0.0,NaN,1,1.0,1.0,18V1
1,MN,1,101,101,1.0,1001.0,2.0,1.0,10004.0,E007,...,Y,199 999,10101.0,NaN,0.0,NaN,1,NaN,1.0,18V1
2,MN,1,201,101,1.0,1000.0,2.0,1.0,10004.0,E007,...,NaN,199 999,10101.0,NaN,0.0,NaN,1,NaN,1.0,18V1
3,MN,1,301,101,NaN,NaN,2.0,1.0,10004.0,E007,...,NaN,199 999,10101.0,NaN,0.0,NaN,4,1.0,1.0,18V1
4,MN,1,401,101,NaN,NaN,2.0,1.0,10004.0,E007,...,NaN,1 99 999,10101.0,NaN,0.0,NaN,4,1.0,1.0,18V1

In [5]:
client_cred = ibm_boto3.client(service_name='s3',
ibm_api_key_id='j6F8sn2qVWVjPrx43UmQkiyEgFx0DIeN_GNqKTFcKKLE',
ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
config=Config(signature_version='oauth'),
endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

bucket = 'edx1-donotdelete-pr-rmsy7vzqm6dj4d'

In [7]:
import numpy as np

In [9]:
#Create a pickle (PKL) file out of the Dataframe:
df_data_1.to_pickle('./df_raw.pkl')
#Upload the pickle (PKL) file:
client_cred.upload_file('./df_raw.pkl',bucket,'df_raw_cos.pkl')

In [10]:
#Download the file from Cloud Object Store:
client_cred.download_file(Bucket=bucket,Key='df_raw_cos.pkl',Filename='./df_raw_local.pkl')
#Create a Dataframe out of the file:
df = pd.read_pickle('./df_raw_local.pkl')
df.head()

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_Flag,PFIRM15_Flag,Version
0,MN,1,10,101,5.0,1011.0,2.0,1.0,10004.0,E007,...,Y,199 999,10101.0,NaN,0.0,NaN,1,1.0,1.0,18V1
1,MN,1,101,101,1.0,1001.0,2.0,1.0,10004.0,E007,...,Y,199 999,10101.0,NaN,0.0,NaN,1,NaN,1.0,18V1
2,MN,1,201,101,1.0,1000.0,2.0,1.0,10004.0,E007,...,NaN,199 999,10101.0,NaN,0.0,NaN,1,NaN,1.0,18V1
3,MN,1,301,101,NaN,NaN,2.0,1.0,10004.0,E007,...,NaN,199 999,10101.0,NaN,0.0,NaN,4,1.0,1.0,18V1
4,MN,1,401,101,NaN,NaN,2.0,1.0,10004.0,E007,...,NaN,1 99 999,10101.0,NaN,0.0,NaN,4,1.0,1.0,18V1

In [13]:
#Download the file from Cloud Object Store:
client_cred.download_file(Bucket=bucket,Key='BK_18v1.csv',Filename='BK_18v1.csv')
#Create a Dataframe out of the file:
df_BK = pd.read_csv('BK_18v1.csv')
df_BK.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,20,22,23,24,25,26,64,65,80) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLAG,PFIRM15_FLAG,Version
0,BK,1,1,302,21.0,NaN,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,NaN,3.000010e+09,11/26/2013,1,1.0,1.0,18V1
1,BK,1,50,302,21.0,2000.0,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,E-231,0.000000e+00,NaN,1,1.0,1.0,18V1
2,BK,1,7501,302,21.0,2000.0,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,NaN,3.000010e+09,03/04/2016,1,1.0,1.0,18V1
3,BK,3,1,302,21.0,3002.0,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,NaN,0.000000e+00,NaN,1,1.0,1.0,18V1
4,BK,3,5,302,21.0,NaN,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,NaN,0.000000e+00,NaN,4,1.0,1.0,18V1

In [14]:
#Download the file from Cloud Object Store:
client_cred.download_file(Bucket=bucket,Key='BX_18v1.csv',Filename='BX_18v1.csv')
#Create a Dataframe out of the file:
df_BX = pd.read_csv('BX_18v1.csv')
df_BX.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,20,22,23,64,65,80) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLAG,PFIRM15_FLAG,Version
0,BX,2260,1,201,19.0,1022.0,7.0,8.0,10454.0,L029,...,NaN,209S016,20901.0,E-143,0.0,NaN,1,NaN,NaN,18V1
1,BX,2260,4,201,19.0,1022.0,7.0,8.0,10454.0,L029,...,NaN,209S016,20901.0,E-143,0.0,NaN,1,NaN,NaN,18V1
2,BX,2260,10,201,19.0,1022.0,7.0,8.0,10454.0,L029,...,NaN,209S016,20901.0,E-143,0.0,NaN,1,NaN,NaN,18V1
3,BX,2260,17,201,19.0,1022.0,7.0,8.0,10454.0,L029,...,NaN,209S016,20901.0,E-143,0.0,NaN,1,NaN,NaN,18V1
4,BX,2260,18,201,19.0,1022.0,7.0,8.0,10454.0,L029,...,NaN,209S016,20901.0,E-143,0.0,NaN,1,NaN,NaN,18V1

In [15]:
#Download the file from Cloud Object Store:
client_cred.download_file(Bucket=bucket,Key='QN_18v1.csv',Filename='QN_18v1.csv')
#Create a Dataframe out of the file:
df_QN = pd.read_csv('QN_18v1.csv')
df_QN.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,20,22,23,64,65,77) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLAG,PFIRM15_FLAG,Version
0,QN,6,1,402,1.0,NaN,30.0,26.0,11101.0,L115,...,Y,401 011,40101.0,NaN,4.000060e+09,09/20/2013,1,1.0,1.0,18V1
1,QN,6,3,402,1.0,1015.0,30.0,26.0,11101.0,L115,...,NaN,401 011,40101.0,NaN,0.000000e+00,NaN,1,1.0,1.0,18V1
2,QN,6,8,402,1.0,1011.0,30.0,26.0,11101.0,L115,...,NaN,401 011,40101.0,NaN,4.000060e+09,08/07/2013,1,1.0,1.0,18V1
3,QN,6,20,402,1.0,NaN,30.0,26.0,11101.0,L115,...,NaN,401 011,40101.0,NaN,4.000060e+09,09/20/2013,1,1.0,1.0,18V1
4,QN,6,30,402,1.0,NaN,30.0,26.0,11101.0,L115,...,NaN,401 011,40101.0,NaN,4.000060e+09,09/08/2017,1,1.0,1.0,18V1

In [16]:
#Download the file from Cloud Object Store:
client_cred.download_file(Bucket=bucket,Key='SI_18v1.csv',Filename='SI_18v1.csv')
#Create a Dataframe out of the file:
df_SI = pd.read_csv('SI_18v1.csv')
df_SI.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,20,22,23,24,64,65,80) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLAG,PFIRM15_FLAG,Version
0,SI,1,10,501,3.0,2000.0,31.0,49.0,10301.0,L078,...,NaN,501 017,50101.0,NaN,0.0,NaN,1,NaN,NaN,18V1
1,SI,1,17,501,3.0,NaN,31.0,49.0,10301.0,L078,...,NaN,501 017,50101.0,NaN,0.0,NaN,1,NaN,NaN,18V1
2,SI,1,18,501,3.0,NaN,31.0,49.0,10301.0,L078,...,NaN,501 017,50101.0,NaN,0.0,NaN,1,NaN,NaN,18V1
3,SI,1,19,501,3.0,NaN,31.0,49.0,10301.0,L078,...,NaN,501 017,50101.0,NaN,0.0,NaN,1,NaN,NaN,18V1
4,SI,1,21,501,3.0,NaN,31.0,49.0,10301.0,L078,...,NaN,501 017,50101.0,NaN,0.0,NaN,1,NaN,NaN,18V1

In [17]:
#Download the file from Cloud Object Store:
client_cred.download_file(Bucket=bucket,Key='MN_18v1.csv',Filename='MN_18v1.csv')
#Create a Dataframe out of the file:
df_MN = pd.read_csv('MN_18v1.csv')
df_MN.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (20,23,24,26,64) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_Flag,PFIRM15_Flag,Version
0,MN,1,10,101,5.0,1011.0,2.0,1.0,10004.0,E007,...,Y,199 999,10101.0,NaN,0.0,NaN,1,1.0,1.0,18V1
1,MN,1,101,101,1.0,1001.0,2.0,1.0,10004.0,E007,...,Y,199 999,10101.0,NaN,0.0,NaN,1,NaN,1.0,18V1
2,MN,1,201,101,1.0,1000.0,2.0,1.0,10004.0,E007,...,NaN,199 999,10101.0,NaN,0.0,NaN,1,NaN,1.0,18V1
3,MN,1,301,101,NaN,NaN,2.0,1.0,10004.0,E007,...,NaN,199 999,10101.0,NaN,0.0,NaN,4,1.0,1.0,18V1
4,MN,1,401,101,NaN,NaN,2.0,1.0,10004.0,E007,...,NaN,1 99 999,10101.0,NaN,0.0,NaN,4,1.0,1.0,18V1

In [19]:
#Download the file from Cloud Object Store:
client_cred.download_file(Bucket=bucket,Key='311_Service_Requests_from_2010_to_Present_min.csv',Filename='311_Service_Requests_from_2010_to_Present_min.csv')
#Create a Dataframe out of the file:
df_311 = pd.read_csv('311_Service_Requests_from_2010_to_Present_min.csv')
df_311.head()

,Unnamed: 0,Unique Key,Created Date,Closed Date,Complaint Type,Location Type,Incident Zip,Incident Address,Street Name,Address Type,City,Status,Resolution Description,Borough,Latitude,Longitude
0,0,45531130,02/02/2020 06:09:17 AM,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,10019.0,426 WEST 52 STREET,WEST 52 STREET,ADDRESS,NEW YORK,Open,The following complaint conditions are still o...,MANHATTAN,40.765132,-73.988993
1,1,45529784,02/02/2020 02:15:24 PM,NaN,UNSANITARY CONDITION,RESIDENTIAL BUILDING,11204.0,1751 67 STREET,67 STREET,ADDRESS,BROOKLYN,Open,The following complaint conditions are still o...,BROOKLYN,40.618484,-73.992673
2,2,45527528,02/02/2020 02:27:41 AM,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11372.0,87-15 37 AVENUE,37 AVENUE,ADDRESS,Jackson Heights,Open,The following complaint conditions are still o...,QUEENS,40.750269,-73.879432
3,3,45530329,02/02/2020 12:13:18 PM,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,10458.0,2405 SOUTHERN BOULEVARD,SOUTHERN BOULEVARD,ADDRESS,BRONX,Open,The following complaint conditions are still o...,BRONX,40.853773,-73.881558
4,4,45528814,02/02/2020 01:59:44 PM,NaN,APPLIANCE,RESIDENTIAL BUILDING,11209.0,223 78 STREET,78 STREET,ADDRESS,BROOKLYN,Open,The following complaint conditions are still o...,BROOKLYN,40.629745,-74.030533

In [20]:
df_311.size

96317488

In [21]:
df_311.dtypes

Unnamed: 0                  int64
Unique Key                  int64
Created Date               object
Closed Date                object
Complaint Type             object
Location Type              object
Incident Zip              float64
Incident Address           object
Street Name                object
Address Type               object
City                       object
Status                     object
Resolution Description     object
Borough                    object
Latitude                  float64
Longitude                 float64
dtype: object

In [27]:
df_311['Created Date'] = pd.to_datetime(df_311['Created Date'])
df_311.head()

,Unnamed: 0,Unique Key,Created Date,Closed Date,Complaint Type,Location Type,Incident Zip,Incident Address,Street Name,Address Type,City,Status,Resolution Description,Borough,Latitude,Longitude
0,0,45531130,2020-02-02 06:09:17,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,10019.0,426 WEST 52 STREET,WEST 52 STREET,ADDRESS,NEW YORK,Open,The following complaint conditions are still o...,MANHATTAN,40.765132,-73.988993
1,1,45529784,2020-02-02 14:15:24,NaN,UNSANITARY CONDITION,RESIDENTIAL BUILDING,11204.0,1751 67 STREET,67 STREET,ADDRESS,BROOKLYN,Open,The following complaint conditions are still o...,BROOKLYN,40.618484,-73.992673
2,2,45527528,2020-02-02 02:27:41,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11372.0,87-15 37 AVENUE,37 AVENUE,ADDRESS,Jackson Heights,Open,The following complaint conditions are still o...,QUEENS,40.750269,-73.879432
3,3,45530329,2020-02-02 12:13:18,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,10458.0,2405 SOUTHERN BOULEVARD,SOUTHERN BOULEVARD,ADDRESS,BRONX,Open,The following complaint conditions are still o...,BRONX,40.853773,-73.881558
4,4,45528814,2020-02-02 13:59:44,NaN,APPLIANCE,RESIDENTIAL BUILDING,11209.0,223 78 STREET,78 STREET,ADDRESS,BROOKLYN,Open,The following complaint conditions are still o...,BROOKLYN,40.629745,-74.030533

In [28]:
df_311.dtypes

Unnamed: 0                         int64
Unique Key                         int64
Created Date              datetime64[ns]
Closed Date                       object
Complaint Type                    object
Location Type                     object
Incident Zip                     float64
Incident Address                  object
Street Name                       object
Address Type                      object
City                              object
Status                            object
Resolution Description            object
Borough                           object
Latitude                         float64
Longitude                        float64
dtype: object

In [30]:
df_311_date=df_311 ['Created Date']

In [31]:
df_311_date.head()

0   2020-02-02 06:09:17
1   2020-02-02 14:15:24
2   2020-02-02 02:27:41
3   2020-02-02 12:13:18
4   2020-02-02 13:59:44
Name: Created Date, dtype: datetime64[ns]

In [35]:
df_311_date.min(skipna=True)

Timestamp('2010-01-01 00:00:00')

In [36]:
df_311_date.max(skipna=True)

Timestamp('2020-02-02 23:58:57')

In [38]:
df_311.sort_values (by='Created Date', ascending = True)

,Unnamed: 0,Unique Key,Created Date,Closed Date,Complaint Type,Location Type,Incident Zip,Incident Address,Street Name,Address Type,City,Status,Resolution Description,Borough,Latitude,Longitude
252214,252214,15636509,2010-01-01 00:00:00,01/06/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,10467.0,3041 HOLLAND AVENUE,HOLLAND AVENUE,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.870179,-73.865262
251419,251419,15635215,2010-01-01 00:00:00,01/15/2010 12:00:00 AM,GENERAL CONSTRUCTION,RESIDENTIAL BUILDING,10459.0,919 PROSPECT AVENUE,PROSPECT AVENUE,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.821710,-73.900789
251420,251420,15635216,2010-01-01 00:00:00,02/16/2010 12:00:00 AM,PLUMBING,RESIDENTIAL BUILDING,11237.0,316 JEFFERSON STREET,JEFFERSON STREET,ADDRESS,BROOKLYN,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.704523,-73.926037
251421,251421,15635217,2010-01-01 00:00:00,01/26/2010 12:00:00 AM,PLUMBING,RESIDENTIAL BUILDING,10451.0,815 GERARD AVENUE,GERARD AVENUE,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.825863,-73.925913
251422,251422,15635218,2010-01-01 00:00:00,01/10/2010 12:00:00 AM,PLUMBING,RESIDENTIAL BUILDING,10457.0,2007 LAFONTAINE AVENUE,LAFONTAINE AVENUE,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.847562,-73.893710
251423,251423,15635219,2010-01-01 00:00:00,01/16/2010 12:00:00 AM,APPLIANCE,RESIDENTIAL BUILDING,10466.0,1135 EAST 224 STREET,EAST 224 STREET,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.882940,-73.848275
251424,251424,15635220,2010-01-01 00:00:00,01/02/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,11103.0,30-36 42 STREET,42 STREET,ADDRESS,ASTORIA,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.762232,-73.914148
251418,251418,15635214,2010-01-01 00:00:00,01/07/2010 12:00:00 AM,PLUMBING,RESIDENTIAL BUILDING,11229.0,1247 AVENUE V,AVENUE V,ADDRESS,BROOKLYN,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.596447,-73.958478
251425,251425,15635221,2010-01-01 00:00:00,01/07/2010 12:00:00 AM,GENERAL CONSTRUCTION,RESIDENTIAL BUILDING,11229.0,1247 AVENUE V,AVENUE V,ADDRESS,BROOKLYN,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.596447,-73.958478
251427,251427,15635223,2010-01-01 00:00:00,01/02/2010 12:00:00 AM,GENERAL CONSTRUCTION,RESIDENTIAL BUILDING,10031.0,644 RIVERSIDE DRIVE,RIVERSIDE DRIVE,ADDRESS,NEW YORK,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.825120,-73.953892
251428,251428,15635224,2010-01-01 00:00:00,02/05/2010 12:00:00 AM,GENERAL CONSTRUCTION,RESIDENTIAL BUILDING,11213.0,1435 CARROLL STREET,CARROLL STREET,ADDRESS,BROOKLYN,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.666621,-73.940307
251429,251429,15635225,2010-01-01 00:00:00,02/16/2010 12:00:00 AM,GENERAL CONSTRUCTION,RESIDENTIAL BUILDING,11220.0,321 44 STREET,44 STREET,ADDRESS,BROOKLYN,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.650631,-74.010397
251430,251430,15635226,2010-01-01 00:00:00,01/10/2010 12:00:00 AM,GENERAL CONSTRUCTION,RESIDENTIAL BUILDING,10472.0,1231 WARD AVENUE,WARD AVENUE,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.829705,-73.877535
251431,251431,15635227,2010-01-01 00:00:00,01/25/2010 12:00:00 AM,GENERAL CONSTRUCTION,RESIDENTIAL BUILDING,10453.0,1482 MONTGOMERY AVENUE,MONTGOMERY AVENUE,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.847411,-73.921147
251432,251432,15635228,2010-01-01 00:00:00,02/16/2010 12:00:00 AM,PLUMBING,RESIDENTIAL BUILDING,11355.0,144-03 BARCLAY AVENUE,BARCLAY AVENUE,ADDRESS,FLUSHING,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.759849,-73.820598
251426,251426,15635222,2010-01-01 00:00:00,01/14/2010 12:00:00 AM,GENERAL CONSTRUCTION,RESIDENTIAL BUILDING,10031.0,584 WEST 152 STREET,WEST 152 STREET,ADDRESS,NEW YORK,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.830510,-73.946448
251433,251433,15635229,2010-01-01 00:00:00,01/09/2010 12:00:00 AM,PAINT - PLASTER,RESIDENTIAL BUILDING,11105.0,20-65 27 STREET,27 STREET,ADDRESS,ASTORIA,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.780020,-73.910348
251417,251417,15635213,2010-01-01 00:00:00,01/25/2010 12:00:00 AM,PLUMBING,RESIDENTIAL BUILDING,10466.0,916 EAST 226 STREET,EAST 226 STREET,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.886435,-73.853580
251415,251415,15635211,2010-01-01 00:00:00,01/11/2010 12:00:00 AM,NONCONST,RESIDENTIAL BUILDING,10455.0,673 DAWSON STREET,DAWSON STREET,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.816513,-73.901935
251401,251401,15635196,2010-01-01 00:00:00,01/06/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,11216.0,802 PARK PLACE,PARK PLACE,ADDRESS,BROOKLYN,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.673472,-73.951264
251402,251402,15635198,2010-01-01 00:00:00,01/02/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,10033.0,554 WEST 184 STREET,WEST 184 STREET,ADDRESS,NEW YORK,Closed,More than one complaint was received for this ...,Unspecified,40.850690,-73.931492
251403,251403,15635199,2010-01-01 00:00:00,01/09/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,11222.0,133 FRANKLIN STREET,FRANKLIN STREET,ADDRESS,BROOKLYN,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.730837,-73.957763
251404,251404,15635200,2010-01-01 00:00:00,01/08/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,11368.0,35-58 97 STREET,97 STREET,ADDRESS,CORONA,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.752488,-73.870282
251405,251405,15635201,2010-01-01 00:00:00,01/05/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,10467.0,234 EAST GUN HILL ROAD,EAST GUN HILL ROAD,ADDRESS,BRONX,Closed,More than one complaint was received for this ...,Unspecified,40.880138,-73.876549
251406,251406,15635202,2010-01-01 00:00:00,01/08/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,11209.0,55 92 STREET,92 STREET,ADDRESS,BROOKLYN,Closed,More than one complaint was received for this ...,Unspecified,40.620792,-74.038929
251416,251416,15635212,2010-01-01 00:00:00,01/27/2010 12:00:00 AM,PLUMBING,RESIDENTIAL BUILDING,10457.0,1814 WEEKS AVENUE,WEEKS AVENUE,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.847129,-73.907337
251407,251407,15635203,2010-01-01 00:00:00,01/02/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,11225.0,941 WASHINGTON AVENUE,WASHINGTON AVENUE,ADDRESS,BROOKLYN,Closed,More than one complaint was received for this ...,Unspecified,40.666413,-73.961553
251409,251409,15635205,2010-01-01 00:00:00,01/08/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,10460.0,846 EAST 175 STREET,EAST 175 STREET,ADDRESS,BRONX,Closed,The Department of Housing Preservation and Dev...,Unspecified,40.840378,-73.889272
251410,251410,15635206,2010-01-01 00:00:00,01/05/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,11225.0,57 LINCOLN ROAD,LINCOLN ROAD,ADDRESS,BROOKLYN,Closed,More than one complaint was received for this ...,Unspecified,40.660994,-73.960122
251411,251411,15635207,2010-01-01 00:00:00,01/06/2010 12:00:00 AM,HEATING,RESIDENTIAL BUILDING,10462.0,2330 NEWBOLD AVENUE,NEWBOLD AVENUE,ADDRESS,BRONX,Closed,More than one complaint was received for this ...,Unspecified,40.833921,-73.847198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,62,45530756,2020-02-02 23:30:26,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
113,113,45528890,2020-02-02 23:30:29,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
369,369,45531409,2020-02-02 23:30:41,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
228,228,45529329,2020-02-02 23:33:42,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
547,547,45529844,2020-02-02 23:33:45,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
456,456,45528487,2020-02-02 23:33:50,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,10039.0,2588 7 AVENUE,7 AVENUE,ADDRESS,NEW YORK,Open,The following complaint conditions are still o...,MANHATTAN,40.824478,-73.937033
200,200,45531416,2020-02-02 23:33:54,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
100,100,45531860,2020-02-02 23:33:56,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
248,248,45530744,2020-02-02 23:33:59,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
152,152,45527925,2020-02-02 23:34:02,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11219.0,1329 50 STREET,50 STREET,ADDRESS,BROOKLYN,Open,The following complaint conditions are still o...,BROOKLYN,40.634009,-73.991922
141,141,45531549,2020-02-02 23:34:04,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
432,432,45527979,2020-02-02 23:34:07,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
219,219,45528415,2020-02-02 23:34:14,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
465,465,45530274,2020-02-02 23:36:59,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
176,176,45531547,2020-02-02 23:36:59,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
639,639,45528871,2020-02-02 23:37:02,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
71,71,45531550,2020-02-02 23:37:02,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
515,515,45527499,2020-02-02 23:37:04,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
263,263,45529866,2020-02-02 23:37:05,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
143,143,45530262,2020-02-02 23:37:07,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
76,76,45532040,2020-02-02 23:37:42,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11214.0,8301 BAY PARKWAY,BAY PARKWAY,ADDRESS,BROOKLYN,Open,The complaint you filed is a duplicate of a co...,BROOKLYN,40.603561,-73.992117
270,270,45529360,2020-02-02 23:43:07,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11373.0,89-21 ELMHURST AVENUE,ELMHURST AVENUE,ADDRESS,Elmhurst,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.747420,-73.876853
619,619,45530794,2020-02-02 23:46:05,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11434.0,129-49 157 STREET,157 STREET,ADDRESS,Jamaica,Open,The following complaint conditions are still o...,QUEENS,40.674489,-73.782001
21,21,45528464,2020-02-02 23:46:12,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11210.0,1655 FLATBUSH AVENUE,FLATBUSH AVENUE,ADDRESS,BROOKLYN,Open,The complaint you filed is a duplicate of a co...,BROOKLYN,40.630096,-73.944757
216,216,45531120,2020-02-02 23:46:43,NaN,ELECTRIC,RESIDENTIAL BUILDING,10457.0,3859 3 AVENUE,3 AVENUE,ADDRESS,BRONX,Open,The following complaint conditions are still o...,BRONX,40.838544,-73.900938
606,606,45528905,2020-02-02 23:47:11,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,10468.0,2625 GRAND CONCOURSE,GRAND CONCOURSE,ADDRESS,BRONX,Open,The complaint you filed is a duplicate of a co...,BRONX,40.865154,-73.895088
653,653,45530811,2020-02-02 23:52:15,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11432.0,88-22 PARSONS BOULEVARD,PARSONS BOULEVARD,ADDRESS,Jamaica,Open,The complaint you filed is a duplicate of a co...,QUEENS,40.706441,-73.802062
565,565,45531570,2020-02-02 23:53:13,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,10453.0,2095 GRAND CONCOURSE,GRAND CONCOURSE,ADDRESS,BRONX,Open,The complaint you filed is a duplicate of a co...,BRONX,40.853858,-73.902469
63,63,45527566,2020-02-02 23:56:06,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,10453.0,2095 GRAND CONCOURSE,GRAND CONCOURSE,ADDRESS,BRONX,Open,The complaint you filed is a duplicate of a co...,BRONX,40.853858,-73.902469
641,641,45531286,2020-02-02 23:58:57,NaN,HEAT/HOT WATER,RESIDENTIAL BUILDING,11208.0,2776 PITKIN AVENUE,PITKIN AVENUE,ADDRESS,BROOKLYN,Open,The complaint you filed is a duplicate of a co...,BROOKLYN,40.675725,-73.869642

In [46]:

df_311_date = df_311_date.sort_values(ascending = True)
df_311_date.head()

#df_311_date = df_311_date.sort_values(ascending = False)

252214   2010-01-01
251414   2010-01-01
251420   2010-01-01
251273   2010-01-01
251422   2010-01-01
Name: Created Date, dtype: datetime64[ns]

In [51]:
#Unique Zip Codes in Bronx PLUTO data
df_BX['ZipCode'].nunique()

26

In [54]:
#df_data_QN.size

#Unique ZipCode in Queens PLUTO data
df_QN['ZipCode'].nunique()
#ZipCodes and counts in Queens PLUTO data
#df_data_QN["Zipcode"].value_counts()

65

In [58]:
#Unempty records count
df_311.isnull()

,Unnamed: 0,Unique Key,Created Date,Closed Date,Complaint Type,Location Type,Incident Zip,Incident Address,Street Name,Address Type,City,Status,Resolution Description,Borough,Latitude,Longitude
0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6019813,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019814,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019815,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019816,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019817,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019823,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019824,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019825,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019826,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019827,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019828,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019829,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019830,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019831,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019832,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
6019833,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019834,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019835,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019836,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019837,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
6019838,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019839,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019840,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019841,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6019842,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [59]:
df_311.shape

(6019843, 16)

In [66]:
df_311.isnull().sum()

Unnamed: 0                     0
Unique Key                     0
Created Date                   0
Closed Date               126657
Complaint Type                 0
Location Type              52824
Incident Zip               80697
Incident Address           52825
Street Name                52825
Address Type               84765
City                       80274
Status                         0
Resolution Description      7826
Borough                        0
Latitude                   80671
Longitude                  80671
dtype: int64

In [68]:
df_311.count()

Unnamed: 0                6019843
Unique Key                6019843
Created Date              6019843
Closed Date               5893186
Complaint Type            6019843
Location Type             5967019
Incident Zip              5939146
Incident Address          5967018
Street Name               5967018
Address Type              5935078
City                      5939569
Status                    6019843
Resolution Description    6012017
Borough                   6019843
Latitude                  5939172
Longitude                 5939172
dtype: int64

In [73]:
df_311.nunique()

Unnamed: 0                6019843
Unique Key                6019843
Created Date              1675132
Closed Date                757706
Complaint Type                 30
Location Type                   5
Incident Zip                  202
Incident Address           182600
Street Name                  6825
Address Type                    1
City                           89
Status                          5
Resolution Description        340
Borough                         6
Latitude                   180072
Longitude                  180072
dtype: int64

In [74]:
#Counts for each complaint type 
df_311['Complaint Type'].value_counts()

HEAT/HOT WATER            1261574
HEATING                    887850
PLUMBING                   711130
GENERAL CONSTRUCTION       500863
UNSANITARY CONDITION       451643
PAINT - PLASTER            361257
PAINT/PLASTER              346438
ELECTRIC                   307310
NONCONST                   260890
DOOR/WINDOW                205278
WATER LEAK                 193631
GENERAL                    151308
FLOORING/STAIRS            137402
APPLIANCE                  112831
HPD Literature Request      52824
SAFETY                      51529
OUTSIDE BUILDING             7142
ELEVATOR                     6725
Unsanitary Condition         5499
CONSTRUCTION                 5078
General                      1163
Safety                        424
STRUCTURAL                     16
Plumbing                       11
AGENCY                          9
Outside Building                6
VACANT APARTMENT                6
Appliance                       4
Electric                        1
Mold                            1
Name: Complaint Type, dtype: int64

In [79]:
df_311_heat = df_311.replace({'Complaint Type': 'HEAT/HOT WATER'},{'Complaint Type':'HEATING'}, regex=True)
df_311_heat = df_311_heat[(df_311_heat['Complaint Type'] == 'HEATING')]

In [80]:
df_311_heat.head()

,Unnamed: 0,Unique Key,Created Date,Closed Date,Complaint Type,Location Type,Incident Zip,Incident Address,Street Name,Address Type,City,Status,Resolution Description,Borough,Latitude,Longitude
0,0,45531130,2020-02-02 06:09:17,NaN,HEATING,RESIDENTIAL BUILDING,10019.0,426 WEST 52 STREET,WEST 52 STREET,ADDRESS,NEW YORK,Open,The following complaint conditions are still o...,MANHATTAN,40.765132,-73.988993
2,2,45527528,2020-02-02 02:27:41,NaN,HEATING,RESIDENTIAL BUILDING,11372.0,87-15 37 AVENUE,37 AVENUE,ADDRESS,Jackson Heights,Open,The following complaint conditions are still o...,QUEENS,40.750269,-73.879432
3,3,45530329,2020-02-02 12:13:18,NaN,HEATING,RESIDENTIAL BUILDING,10458.0,2405 SOUTHERN BOULEVARD,SOUTHERN BOULEVARD,ADDRESS,BRONX,Open,The following complaint conditions are still o...,BRONX,40.853773,-73.881558
5,5,45530344,2020-02-02 07:52:08,NaN,HEATING,RESIDENTIAL BUILDING,10456.0,1131 MORRIS AVENUE,MORRIS AVENUE,ADDRESS,BRONX,Open,The following complaint conditions are still o...,BRONX,40.831381,-73.915218
7,7,45527939,2020-02-02 09:00:54,NaN,HEATING,RESIDENTIAL BUILDING,11372.0,37-20 81 STREET,81 STREET,ADDRESS,Jackson Heights,Open,The following complaint conditions are still o...,QUEENS,40.749320,-73.885190

In [78]:
df_311_heat["Closed Date"].count()

NameError: name 'df_311_heat' is not defined

In [82]:
df_311_heat.shape

(2149424, 16)

In [85]:
df_311_heat['Borough'].value_counts()

BRONX            606133
BROOKLYN         574845
MANHATTAN        423039
Unspecified      282917
QUEENS           244122
STATEN ISLAND     18368
Name: Borough, dtype: int64

In [87]:
df_311_heat['Incident Zip'].value_counts()

11226.0    69041
10467.0    66073
10458.0    65372
10468.0    58190
10453.0    57818
10452.0    49802
10457.0    46885
10031.0    44777
10040.0    44478
10456.0    44051
11225.0    43077
11213.0    40333
10462.0    39700
10463.0    37702
10032.0    36394
11212.0    34619
10472.0    33718
10033.0    33180
10460.0    33026
11233.0    30814
11203.0    29359
11221.0    28380
10451.0    26537
11216.0    26433
11207.0    26428
10034.0    26375
10025.0    24844
10466.0    24220
10027.0    23740
11373.0    23665
           ...
11426.0      326
10309.0      317
11362.0      315
11004.0      248
10007.0      227
10006.0      202
10308.0      195
10005.0      181
10307.0      178
10004.0      161
10282.0      155
11001.0      121
10280.0       72
11697.0       66
11040.0       57
11109.0       23
10069.0       23
11005.0        8
10162.0        5
10803.0        4
10041.0        3
10020.0        3
11430.0        2
10169.0        2
10045.0        1
10103.0        1
10112.0        1
10121.0        1
10129.0        1
12345.0        1
Name: Incident Zip, Length: 193, dtype: int64

In [89]:
df_311_heat['Incident Address'].value_counts()

34 ARDEN STREET                   13858
89-21 ELMHURST AVENUE             11548
3810 BAILEY AVENUE                 7115
1025 BOYNTON AVENUE                5785
9511 SHORE ROAD                    5006
2090 EAST TREMONT AVENUE           3792
72-10 41 AVENUE                    3493
888 GRAND CONCOURSE                3251
2968 PERRY AVENUE                  2992
1711 FULTON STREET                 2794
2074 WALLACE AVENUE                2737
2750 HOMECREST AVENUE              2722
1030 BOYNTON AVENUE                2631
97 SHERMAN AVENUE                  2560
266 BEDFORD PARK BOULEVARD         2530
2040 BRONXDALE AVENUE              2480
1425 DR M L KING JR BOULEVARD      2353
750 GRAND CONCOURSE                2266
2176 TIEBOUT AVENUE                2209
30 BUCHANAN PLACE                  2033
957 WOODYCREST AVENUE              1895
3605 SEDGWICK AVENUE               1876
2856 WEBB AVENUE                   1823
109 NORTH    7 STREET              1712
2645 MORRIS AVENUE                 1688
116 EAST MOSHOLU PARKWAY SOUTH     1669
2410 WASHINGTON AVENUE             1637
170 HAWTHORNE STREET               1537
712 CROWN STREET                   1519
2913 FOSTER AVENUE                 1490
                                  ...
1335 EAST 85 STREET                   1
4014 GLENWOOD ROAD                    1
364 EAST  167 STREET                  1
43-25 76 STREET                       1
127 EAST   36 STREET                  1
77-05 156 AVENUE                      1
7 9 AVENUE                            1
243 3 AVENUE                          1
843 57 STREET                         1
1423 ALBANY AVENUE                    1
250 WEST 76 STREET                    1
9712 KINGS HIGHWAY                    1
69-07 BAYFIELD AVENUE                 1
739 EAST   38 STREET                  1
771 41 STREET                         1
4-09 121 STREET                       1
2030 WEST    4 STREET                 1
1512 LIBRARY AVENUE                   1
1214 EAST 82 STREET                   1
85 EAST   46 STREET                   1
60-18 FRESH POND ROAD                 1
22 WINTHROP STREET                    1
1673 EAST 35 STREET                   1
106-11 LIBERTY AVENUE                 1
51-11 102 STREET                      1
250 12 STREET                         1
800 SOUTH OAK DRIVE                   1
98 JULES DRIVE                        1
339 EAST 58 STREET                    1
3703 HARLEM RIVER DRIVE               1
Name: Incident Address, Length: 136949, dtype: int64

In [91]:
df_311_heat['Closed Date'].count()

2133429

In [94]:
df_BK.columns

Index(['Borough', 'Block', 'Lot', 'CD', 'CT2010', 'CB2010', 'SchoolDist',
       'Council', 'ZipCode', 'FireComp', 'PolicePrct', 'HealthCenterDistrict',
       'HealthArea', 'SanitBoro', 'SanitDistrict', 'SanitSub', 'Address',
       'ZoneDist1', 'ZoneDist2', 'ZoneDist3', 'ZoneDist4', 'Overlay1',
       'Overlay2', 'SPDist1', 'SPDist2', 'SPDist3', 'LtdHeight', 'SplitZone',
       'BldgClass', 'LandUse', 'Easements', 'OwnerType', 'OwnerName',
       'LotArea', 'BldgArea', 'ComArea', 'ResArea', 'OfficeArea', 'RetailArea',
       'GarageArea', 'StrgeArea', 'FactryArea', 'OtherArea', 'AreaSource',
       'NumBldgs', 'NumFloors', 'UnitsRes', 'UnitsTotal', 'LotFront',
       'LotDepth', 'BldgFront', 'BldgDepth', 'Ext', 'ProxCode', 'IrrLotCode',
       'LotType', 'BsmtCode', 'AssessLand', 'AssessTot', 'ExemptLand',
       'ExemptTot', 'YearBuilt', 'YearAlter1', 'YearAlter2', 'HistDist',
       'Landmark', 'BuiltFAR', 'ResidFAR', 'CommFAR', 'FacilFAR', 'BoroCode',
       'BBL', 'CondoNo', 'Tract2010', 'XCoord', 'YCoord', 'ZoneMap', 'ZMCode',
       'Sanborn', 'TaxMap', 'EDesigNum', 'APPBBL', 'APPDate', 'PLUTOMapID',
       'FIRM07_FLAG', 'PFIRM15_FLAG', 'Version'],
      dtype='object')